theme: jekyll-theme-minimal
title: Charlie Zhang
logo: 

author: 
  name: Charlie Zhang
  
description:  # this means to ignore newlines until "baseurl:"
  MS-DSPP 22' @ Georgetown University
  cz317 at georgetown.edu

blog: true

github:
  is_project_page: false
  is_user_page: false
